# Generated by Django 3.2.13 on 2022-04-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeAfrikaSchoolAPI_Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_teaching_lesson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_taking_lesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
