# Generated by Django 3.2.13 on 2022-04-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CodeAfrikaSchoolAPI_Posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeAFrikaSChoolAPI_Topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAfrikaSchoolAPI_Posts.post'),
        ),
    ]
