# Generated by Django 3.2.13 on 2022-04-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CodeAfrikaSchoolAPI_Communities', '0001_initial'),
        ('CodeAfrikaSchoolAPI_Courses', '0001_initial'),
        ('CodeAfrikaSchoolAPI_Projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeAFrikaSChoolAPI_Topics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_of_thiscommunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='courses',
            field=models.ManyToManyField(to='CodeAfrikaSchoolAPI_Courses.Course'),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='members_of_thiscommunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='projects',
            field=models.ManyToManyField(to='CodeAfrikaSchoolAPI_Projects.Project'),
        ),
        migrations.AddField(
            model_name='community',
            name='topics',
            field=models.ManyToManyField(to='CodeAFrikaSChoolAPI_Topics.Topic'),
        ),
    ]
