# Generated by Django 3.2.13 on 2022-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('content', models.TextField()),
                ('post_type', models.PositiveSmallIntegerField(choices=[(1, 'question_post'), (2, 'general_post')], primary_key=True, serialize=False)),
            ],
        ),
    ]
