# Generated by Django 3.2.13 on 2022-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('practical_assesment', models.TextField()),
                ('course_category', models.PositiveSmallIntegerField(choices=[(1, 'instructor_led'), (2, 'on_demand')], primary_key=True, serialize=False)),
                ('difficulty_level', models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
            ],
        ),
    ]
