# Generated by Django 3.2.13 on 2022-04-28 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CodeAfrikaSchoolAPI_Courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeAfrikaSchoolAPI_Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='candidates',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='CodeAfrikaSchoolAPI_Lessons.Lesson'),
        ),
    ]
